# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Pet'),
        ),
    ]
