# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
