# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
