# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20171104_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Pet'),
        ),
    ]
